app/tarea/urls.py
from django.urls import path
from django.contrib.auth import views as av
from . import views

app_name = 'tarea'
urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),

  path('login/', av.LoginView.as_view(), name='login'),
  path('logout/', av.LogoutView.as_view(), name='logout'),
  path('password_change/', av.PasswordChangeView.as_view(), name='password_change'),
  path('password_change/done/', av.PasswordChangeDoneView.as_view(), name='password_change_done'),

  path('profile/', views.UserProfileView.as_view(), name="profile"),
  path('create/', views.UserCreateView.as_view(), name="create"),

  path('new/', views.new, name="new"),
  path('task/<int:pk>/', views.DetailView.as_view(), name='detail'),
  path('task/<int:pk>/edit', views.edit, name='edit'),
  path('task/<int:pk>/delete', views.delete, name='delete'),
  path('task/uncomplete/<int:pk>', views.uncomplete, name="uncomplete"),
  path('task/complete/<int:pk>', views.complete, name="complete"),
]

app/tarea_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tarea.urls')),
    path('admin/', admin.site.urls),
]

app/tarea/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.core.validators import MinLengthValidator
from django.contrib.auth import get_user_model

class User(models.Model):
  username = models.CharField(max_length=50)

  def __str__(self): 
    return self.username

class Task(models.Model):
  title = models.CharField(max_length=20)
  pub_date = models.DateTimeField(default=timezone.now)
  caption = models.TextField(max_length=255)
  completed = models.BooleanField(default=False)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
  

  def __str__(self): 
    return self.title

app/tarea/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, FormView

from .models import Task, User

class UserCreateView(FormView):
  form_class = UserCreationForm
  template_name = 'registration/create.html'
  success_url = reverse_lazy('tarea:profile')
  def form_valid(self, form):
    print(self.request.POST['next'])
    if self.request.POST['next'] == 'back':
      return render(self.request, 'registration/create.html', {'form': form})
    elif self.request.POST['next'] == 'confirm':
      return render(self.request, 'registration/create_confirm.html', {'form': form})
    elif self.request.POST['next'] == 'regist':
      form.save()
      user = authenticate(
        username=form.cleaned_data['username'],
        password=form.cleaned_data['password1'],
      )
      login(self.request, user)
      return super().form_valid(form)
    else:
      return redirect(reverse_lazy('tarea:index'))

class UserProfileView(LoginRequiredMixin, TemplateView):
  template_name = 'registration/profile.html'
  def get_queryset(self):
    return User.objects.get(id=self.request.user.id)

class IndexView(ListView):
  model = User, Task
  template_name = 'tarea/tasks/index.html'
  context_object_name = 'task_list'

  def get_queryset(self):
    return Task.objects.order_by('-pub_date')

class DetailView(DetailView):
  model = Task
  template_name = 'tarea/tasks/detail.html'

@login_required

def new(request):
  model = User, Task
  template_name = "tarea/tasks/new.html"
  if request.method == "POST":
    task = Task(
      title=request.POST["title"],
      caption=request.POST["caption"],
      pub_date=timezone.now(),
      user=request.user
      )
    task.save()
    return redirect('tarea:index')
  return render(request, template_name)

def edit(request, pk):
  template_name = "tarea/tasks/edit.html"
  task = get_object_or_404(Task, pk=pk)
  if request.method == "POST":
    task.title = request.POST["title"]
    task.caption = request.POST["caption"]
    task.save()
    return redirect('tarea:detail', pk=pk)
  context = {"task": task}
  return render(request, template_name, context)

def delete(request, pk):
  task = get_object_or_404(Task, pk=pk)
  task.delete()
  return redirect('tarea:index')

def uncomplete(request, pk):
  task = get_object_or_404(Task, pk=pk)
  task.completed = False
  task.save()
  return redirect('tarea:index')

def complete(request, pk):
  task = get_object_or_404(Task, pk=pk)
  task.completed = True
  task.save()
  return redirect('tarea:index')

app/tarea/templates/tarea/commons/base.html
{% load static %}
{% bootstrap_css %}
{% load fontawesome_5 %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'tarea/css/custom.css' %}">
    <title>{% block title %}Tarea{% endblock %}</title>
    {% fontawesome_5_static %} 
  </head>

  <body>

    {% block header %}
      <header class="fixed-top navbar-light navibar">
        <nav class="navbar navbar-expand-sm">
          <a href="/" class="navbar-brand"><img src="{% static 'tarea/logo.jpg' %}" class="logo"></a>
          <a href="/" class="navbar-brand">Tarea</a>
          <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="nav navbar-nav ml-auto">
              {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'tarea:new' %}" class="nav-link">タスクの追加</a></li> 
                <li class="nav-item"><a href="{% url 'tarea:profile' %}" class="nav-link">ユーザー情報</a></li> 
                <li class="nav-item"><a href="{% url 'tarea:logout' %}" class="nav-link">ログアウト</a></li> 
                {% else %}
                <li class="nav-item"><a href="{% url 'tarea:login' %}" class="nav-link">ログイン</a></li> 
                <li class="nav-item"><a href="{% url 'tarea:create' %}" class="nav-link">ユーザー登録</a></li> 
              {% endif %}
            </ul>
          </div>
        </nav>
      </header> 
    {% endblock %}


    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

  </body>
</html>

app/tarea/templates/tarea/tasks/detail.html
{% extends 'tarea/commons/base.html' %}

{% block content %}
  <p>
    {{ task.title }}
  </p>
  <p>
    {{ task.caption }}
  </p>
  <div class="d-flex">
    <a href="{% url 'tarea:edit' task.pk %}">
      <button class="icon"><i class="fa fa-pen fa-2x" aria-hidden="true"></i></button>
    </a>
    <a href="{% url 'tarea:delete' task.pk %}">
      <button class="icon"><i class="fa fa-trash fa-2x" aria-hidden="true"></i></button>
    </a>
  </div>
{% endblock %}

app/tarea/templates/tarea/tasks/edit.html
{% extends 'tarea/commons/base.html' %}

{% block content %}
  <h2>taskの編集</h2>

  <form action="" method="post">
    <p><label for="title_input">task名</label></p>
    <p><input type="text" name="title" id="title_input" value="{{ task.title }}"></p>
    <p><label for="caption_input">task内容</label></p>
    <p><textarea type="text" name="caption" id="caption_input" placeholder="{{ task.caption }}"></textarea></p>
    <div class="d-flex justify-content-center align-items-end mt-3">
      <p class="text-center"><button type="submit" class="button py-2 px-4">更新</button></p>
      <p class="text-center ml-3"><a href="{% url 'tarea:detail' task.pk %}" class="button-csl py-2 px-3">キャンセル</a></p>
    </div>
    {% csrf_token %}
  </form>
{% endblock %}

app/tarea/templates/tarea/tasks/index.html
{% extends 'tarea/commons/base.html' %}

{% block content %}
  {% if user.is_authenticated  %}

    <p>こんにちは，{{ user.username }}さん</p>

    <h2>Task</h2>
    
    {% for task in task_list %}
      {% if task.completed %}
      {% else %}
        <div class="task-container my-3 d-flex justify-content-between align-items-baseline">
          <a href="{% url 'tarea:detail' task.id %}" class="flex-grow-1 title pl-4">{{ task.title }}</a>
          <a href="{% url 'tarea:complete' task.id %}" class="resp">完了</a>
          <p class="date text-right mb-0 px-4" style="width: 16rem;">{{ task.user }}, {{ task.pub_date|date:"n/j H:i"}}</p>
        </div>
      {% endif %}
    {% endfor %}

    </br>
    
    <h2>Complete</h2>

    {% for task in task_list %}
      {% if task.completed %}
        <div class="task-container striker my-3 d-flex justify-content-between align-items-baseline">
          <a href="{% url 'tarea:detail' task.id %}" class="flex-grow-1 title pl-4">{{ task.title }}</a>
          <a href="{% url 'tarea:uncomplete' task.id %}">未完了</a>
          <p class="date text-right mb-0 px-4" style="width: 16rem;">{{ task.user }}, {{ task.pub_date|date:"n/j H:i"}}</p>
        </div>
      {% endif %}
    {% endfor %}

  {% else %}

    <div>
      <p class="caption text-center p-4">Tareaは簡単なタスク投稿アプリです！</p>
      
      <div class="d-flex justify-content-center">
        <p class="text-center"><a href="{% url 'tarea:create' %}" class="button-csl py-2 px-3">新規登録して使ってみる</a></p>
        <p class="text-center pl-4"><a href="{% url 'tarea:login' %}" class="button py-2 px-3">ログインして使ってみる</a></p>
      </div>
    </div>

  {% endif %}
{% endblock %}

app/tarea/templates/tarea/tasks/new.html
{% extends 'tarea/commons/base.html' %}

{% block content %}
  <h2>taskの追加</h2>

  <form action="" method="post">
    <p><label for="title_input">task内容</label></p>
    <p><input type="text" name="title" id="title_input"></p>
    <p><label for="caption_input">task内容</label></p>
    <p><textarea type="text" name="caption" id="caption_input" placeholder="{{ task.caption }}"></textarea></p>
    <p><button type="submit" class="button py-1 px-3">投稿</button></p>
    {% csrf_token %}
  </form>
{% endblock %}